name: Firebase Test Lab

on:
  workflow_dispatch:
  
jobs:
  build_test_report:
    name: Build → Test → Report
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Checkout Fenix
        uses: actions/checkout@v3
        with:
          repository: mozilla-mobile/fenix
      - name: Set up JDK 11
        uses: actions/setup-java@v3.4.1
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Setup Gradle Build Action
        uses: gradle/gradle-build-action@v2.2.4
        with: 
          arguments: clean app:assembleDebug app:assembleDebugAndroidTest
      - name: Flank Run
        uses: Flank/flank@master
        with: 
          version: v22.05.0
          service_account: ${{ secrets.SERVICE_ACCOUNT }}
          platform: android
          flank_configuration_file: '${{ github.workspace }}/flank-x86.yml'
